// <auto-generated />
using System;
using HallBooking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HallBooking.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260204092558_SeedMoreTestData")]
    partial class SeedMoreTestData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HallBooking.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("InstructorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("instructor_name");

                    b.Property<decimal>("PricePerParticipant")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("price_per_participant");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_courses");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("HallBooking.Entities.CourseEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.HasKey("Id")
                        .HasName("pk_course_enrollments");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_course_enrollments_course_id");

                    b.HasIndex("MemberId", "CourseId")
                        .IsUnique()
                        .HasDatabaseName("ix_course_enrollments_member_id_course_id");

                    b.ToTable("course_enrollments", (string)null);
                });

            modelBuilder.Entity("HallBooking.Entities.CourseSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("pk_course_sessions");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_course_sessions_course_id");

                    b.HasIndex("StartTime", "EndTime")
                        .HasDatabaseName("ix_course_sessions_start_time_end_time");

                    b.ToTable("course_sessions", (string)null);
                });

            modelBuilder.Entity("HallBooking.Entities.HallRental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<decimal>("HourlyPrice")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("hourly_price");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_hall_rentals");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_hall_rentals_member_id");

                    b.ToTable("hall_rentals", (string)null);
                });

            modelBuilder.Entity("HallBooking.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_members");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_members_email");

                    b.ToTable("members", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anna@mail.com",
                            Name = "Anna Andersson"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "brotherbear@mail.com",
                            Name = "Björn Berg"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cissi@example.com",
                            Name = "Cecilia Carlsson"
                        });
                });

            modelBuilder.Entity("HallBooking.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("amount");

                    b.Property<int?>("CourseEnrollmentId")
                        .HasColumnType("integer")
                        .HasColumnName("course_enrollment_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("HallRentalId")
                        .HasColumnType("integer")
                        .HasColumnName("hall_rental_id");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("CourseEnrollmentId")
                        .HasDatabaseName("ix_payments_course_enrollment_id");

                    b.HasIndex("HallRentalId")
                        .HasDatabaseName("ix_payments_hall_rental_id");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_payments_member_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("HallBooking.Entities.CourseEnrollment", b =>
                {
                    b.HasOne("HallBooking.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_enrollments_courses_course_id");

                    b.HasOne("HallBooking.Entities.Member", "Member")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_enrollments_members_member_id");

                    b.Navigation("Course");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("HallBooking.Entities.CourseSession", b =>
                {
                    b.HasOne("HallBooking.Entities.Course", "Course")
                        .WithMany("Sessions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_sessions_courses_course_id");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("HallBooking.Entities.HallRental", b =>
                {
                    b.HasOne("HallBooking.Entities.Member", "Member")
                        .WithMany("HallRentals")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hall_rentals_members_member_id");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("HallBooking.Entities.Payment", b =>
                {
                    b.HasOne("HallBooking.Entities.CourseEnrollment", "CourseEnrollment")
                        .WithMany("Payments")
                        .HasForeignKey("CourseEnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_payments_course_enrollments_course_enrollment_id");

                    b.HasOne("HallBooking.Entities.HallRental", "HallRental")
                        .WithMany("Payments")
                        .HasForeignKey("HallRentalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_payments_hall_rentals_hall_rental_id");

                    b.HasOne("HallBooking.Entities.Member", "Member")
                        .WithMany("Payments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_members_member_id");

                    b.Navigation("CourseEnrollment");

                    b.Navigation("HallRental");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("HallBooking.Entities.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("HallBooking.Entities.CourseEnrollment", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("HallBooking.Entities.HallRental", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("HallBooking.Entities.Member", b =>
                {
                    b.Navigation("CourseEnrollments");

                    b.Navigation("HallRentals");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
